In [3]:
## Creating Arrays
import numpy as np
array_1 = np.array([5,1,2])
array_2 = np.array([(2.3,1,4), (3,2,7)], dtype = float)
array_3 = np.array([1,3,5], dtype = float)
print(array_2)

[[2.3 1.  4. ]
 [3.  2.  7. ]]


#### Initial Placeholders

In [4]:
np.zeros((2,3)) # Create an array of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2,3),dtype=np.int16) # Create an array of ones

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [6]:
np.arange(15,33,4) # Create an array of evenly spaced values (step value)

array([15, 19, 23, 27, 31])

In [7]:
np.linspace(0,4,9) # Create an array of evenly spaced values (number of samples)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [8]:
np.full((3,4),5) # Create a constant array

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [9]:
np.eye(4) # Create a 4X4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.random((3,4)) # Create an array with random values

array([[0.74422529, 0.62179862, 0.74585988, 0.86113047],
       [0.78248616, 0.43511154, 0.214791  , 0.83289161],
       [0.48616351, 0.44493628, 0.11512202, 0.87083979]])

#### Saving & Loading On Disk

In [11]:
## IO
import os
os.getcwd()
np.save('my_array', array_1)
np.savez('array.npz', array_1, array_2)
np.load('my_array.npy')

# Saving & Loading Text Files
np.savetxt("myarray.txt", array_2, delimiter="\t")
np.loadtxt("myarray.txt")

array([[2.3, 1. , 4. ],
       [3. , 2. , 7. ]])

In [12]:
os.getcwd()

'C:\\Users\\Babak\\slide'

In [13]:
## Data Type
#np.int64 # Signed 64-bit integer types
#np.float32 # Standard double-precision floating point
#np.bool # Boolean type storing TRUE and FALSE values
#np.string_ # Fixed-length string type
#np.unicode_ # Fixed-length unicode type

#### Inspecting Your Array

In [14]:
array_2.shape # Array dimensions
len(array_2) # Length of array
array_2.ndim # Number of array dimensions
array_2.size # Number of array elements
array_2.dtype # Data type of array elements
array_2.dtype.name # Name of data type
array_2.astype(int) # Convert an array to a different type

array([[2, 1, 4],
       [3, 2, 7]])

In [18]:
## Asking For Help
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [19]:
array_2.astype(int)

array([[2, 1, 4],
       [3, 2, 7]])

#### Array Mathematics
#### Arithmetic Operations

In [20]:
array_1 - array_2 # Subtraction: np.subtract(array_1,array_2)
array_2 + array_1 # Addition: np.add(array_2,array_1)
array_1 / array_2 # Division: np.divide(array_1,array_2)
array_1 * array_2 # Multiplication: np.multiply(array_1,array_2)
np.log(array_1) # Element-wise natural logarithm
np.inner(array_1,array_3) # Dot product

18.0

In [17]:
np.log(array_1)

array([1.60943791, 0.        , 0.69314718])

In [21]:
# Comparison
array_1 == array_2 # Element-wise comparison
array_1 < 2 # Element-wise comparison
np.array_equal(array_1, array_2) # Array-wise comparison
np.array_equal(array_1, array_3) # Array-wise comparison

False

In [22]:
# Aggregate Functions
array_1.sum() # Array-wise sum
array_1.min() # Array-wise minimum value
array_2.max(axis=0) # Maximum value of an array row
array_2.cumsum(axis=1) # Cumulative sum of the elements
array_1.mean() # Mean
np.corrcoef(array_1,array_3) # Correlation coefficient
np.corrcoef(array_2) # Correlation coefficient
np.std(array_2) # Standard deviation

1.9238993967691993

In [23]:
np.std(array_2)

1.9238993967691993

In [24]:
array_2.cumsum(axis=1)

array([[ 2.3,  3.3,  7.3],
       [ 3. ,  5. , 12. ]])

In [25]:
## Copying Arrays
array_4=array_1.view() # Create a view of the array with the same data
array_4[1]=10
array_1
array_4[1]=2
np.copy(array_1) # Create a copy of the array

array([5, 2, 2])

In [26]:
array_1

array([5, 2, 2])

In [27]:
## Sorting Arrays
array_3.sort() # Sort an array

In [28]:
## Subsetting, Slicing, Indexing
# Subsetting
array_1[2] # Select the element at the 2nd index
array_2[1,2] # Select the element at row 1 column 2, equivalent to array_2[1][2]
# Slicing
array_1[0:2] # Select items at index 0 and 1
array_2[0:2,1] # Select items at rows 0 and 1 in column 1
array_2[:1] # Select all items at row 0
# Boolean Indexing
array_1[array_1<2] # Select elements from a less than 2
# Fancy Indexing
array_2[[1, 0, 1, 0],[0, 1, 2, 0]] # Select elements (1,0),(0,1),(1,2) and (0,0)

array([3. , 1. , 7. , 2.3])

In [29]:
array_2

array([[2.3, 1. , 4. ],
       [3. , 2. , 7. ]])

In [30]:
array_2[[1, 0, 1, 0],[0, 1, 2, 0]]

array([3. , 1. , 7. , 2.3])

In [31]:
## Array Manipulation
# Transposing Array
i = np.transpose(array_2) # Permute array dimensions
i.T # Permute array dimensions
# Changing Array Shape
array_2.ravel() # Flatten the array
np.array([9,7,4,1,3,8]).reshape(2,3) # Reshape, but don’t change data
# Adding/Removing Elements
np.append(array_1,array_2) # Append items to an array
np.insert(array_1, 1, 5) # Insert items in an array
np.delete(array_1,[1]) # Delete items from an array

array([5, 2])

In [32]:
np.delete(array_1,[1])

array([5, 2])

In [33]:
############################################
########## SciPy - Linear Algebra ##########
############################################
# Sparse matrix